DELETE FROM mysql.user;
CREATE USER 'root'@'%' IDENTIFIED BY 'Km7Iv80l';
GRANT ALL ON *.* TO 'root'@'%' WITH GRANT OPTION ;
DROP DATABASE IF EXISTS test;
CREATE DATABASE test;
FLUSH PRIVILEGES;
FLUSH TABLES;
